AWSTemplateFormatVersion: '2010-09-09'
Description: A starter AWS Lambda function.
Resources:
  helloworldpython3:
    Properties:
      CodeUri: s3://aws-course-sam-bucket-hr/214470635772d4c0dd3154d68189391e
      Description: A starter AWS Lambda function.
      Handler: main.lambda_handler
      MemorySize: 128
      Runtime: python3.6
      Timeout: 3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
